name = "clip_rendering_and_sprite_sheets"
description = ""
version = "0.1.0-dev"

authors = ["Jose Alexis Paez"]
maintainers = ["Jose Alexis Paez <jose.alexis.paez.thurgood@gmail.com>"]
maintainers-logins = ["alexispaez"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["clip_rendering_and_sprite_sheets"]

[[depends-on]]
sdlada = "^2.5.124"

[[pins]]
sdlada = { url='https://github.com/ada-game-framework/sdlada.git' }

[[depends-on]]
sdlada_mixer = "^2.5.22"

[[pins]]
sdlada_mixer = { url='https://github.com/ada-game-framework/sdlada_mixer.git' }

[[depends-on]]
sdlada_image = "~0.1.0-dev"

[[pins]]
sdlada_image = { url='https://github.com/ada-game-framework/sdlada_image.git' }

[[depends-on]]
sdlada_ttf = "~0.1.0-dev"

[[pins]]
sdlada_ttf = { url='https://github.com/ada-game-framework/sdlada_ttf.git' }
