name = "key_presses"
description = "Control key presses with sdlada"
version = "0.1.0-dev"

authors = ["Jose Alexis Paez"]
maintainers = ["Jose Alexis Paez <jose.alexis.paez.thurgood@gmail.com>"]
maintainers-logins = ["alexispaez"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["key_presses"]

[[depends-on]]
sdlada = "^2.5.124"

[[pins]]
sdlada = { url='https://github.com/ada-game-framework/sdlada.git' }
